export const data = [
  {
    id: 1,
    question: "What is the capital of France?",
    options: ["Paris", "paris", "PARIS"],
    answer: ["Paris"],
    multipleAnswers: false,
  },
  {
    id: 2,
    question: "What is the capital of Germany?",
    options: ["Berlin", "berlin", "BERLIN"],
    answer: ["berlin", "BERLIN"],
    multipleAnswers: true,
  },
  {
    id: 3,
    question: "What is the capital of Italy?",
    options: ["Rome", "rome", "ROME"],
    answer: ["Rome"],
    multipleAnswers: false,
  },
  {
    id: 4,
    question: "What is the capital of Spain?",
    options: ["Madrid", "madrid", "MADRID"],
    answer: ["Madrid", "madrid", "MADRID"],
    multipleAnswers: true,
  },
  {
    id: 5,
    question: "What is the capital of Portugal?",
    options: ["Lisbon", "lisbon", "LISBON"],
    answer: ["lisbon"],
    multipleAnswers: false,
  },
  {
    id: 6,
    question: "What is the capital of Belgium?",
    options: ["Brussels", "brussels", "BRUSSELS"],
    answer: ["brussels", "BRUSSELS"],
    multipleAnswers: true,
  },
  {
    id: 7,
    question: "What is the capital of Netherlands?",
    options: ["Amsterdam", "amsterdam", "AMSTERDAM"],
    answer: ["Amsterdam", "amsterdam", "AMSTERDAM"],
    multipleAnswers: true,
  },
];
