name = "google-gemini-competition"
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2024-06-14"
compatibility_flags = ["nodejs_compat"]